'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TextbasedHangover.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property minimap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap10x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap10x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap10y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap10y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap11x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap11x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap11y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap11y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap12x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap12x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap12y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap12y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap13x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap13x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap13y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap13y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap14x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap14x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap14y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap14y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap15x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap15x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap15y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap15y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap16y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap16y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap17x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap17x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap17y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap17y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap18x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap18x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap18y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap18y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap19x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap19x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap19y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap19y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap1y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap1y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap20x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap20x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap20y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap20y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap21x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap21x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap21y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap21y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap23x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap23x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap23y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap23y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap24x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap24x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap24y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap24y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap25x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap25x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap25y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap25y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap26x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap26x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap26y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap26y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap27x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap27x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap27y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap27y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap28x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap28x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap28y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap28y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap29x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap29x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap29y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap29y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap2y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap2y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap30x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap30x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap30y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap30y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap32x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap32x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap32y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap32y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap33x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap33x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap33y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap33y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap34x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap34x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap34y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap34y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap36x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap36x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap36y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap36y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap37x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap37x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap37y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap37y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap38x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap38x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap38y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap38y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap39x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap39x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap39y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap39y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap3x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap3x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap3y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap3y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap41x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap41x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap41y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap41y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap43x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap43x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap43y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap43y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap44x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap44x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap44y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap44y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap45x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap45x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap45y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap45y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap49x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap49x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap49y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap49y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap4x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap4x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap4y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap4y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap50x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap50x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap50y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap50y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap51x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap51x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap51y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap51y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap52x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap52x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap52y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap52y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap53x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap53x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap53y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap53y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap54x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap54x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap54y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap54y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap55x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap55x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap55y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap55y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap56x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap56x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap56y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap56y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap57x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap57x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap57y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap57y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap58x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap58x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap58y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap58y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap59x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap59x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap59y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap59y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap5x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap5x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap5y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap5y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap60x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap60x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap60y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap60y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap61() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap61", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap6x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap6x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap6y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap6y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap7x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap7x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap7y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap7y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap8x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap8x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap8y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap8y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap9x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap9x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimap9y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimap9y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimaps1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimaps1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimaps2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimaps2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimaps3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimaps3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property paint1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paint1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pic1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
